const ADD_ACTIVITY = "ADD_ACTIVITY";
const EDIT_ACTIVITY = "EDIT_ACTIVITY";
const DELETE_ACTIVITY = "DELETE_ACTIVITY";
const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
const SORT_ASC = "SORT_ASC";
const SORT_DES = "SORT_DES";
export {
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  DELETE_ACTIVITY,
  SET_DISPLAY_NAME,
  SORT_ASC,
  SORT_DES
};
