const ADD_ACTIVITY = "ADD_ACTIVITY";
const EDIT_ACTIVITY = "EDIT_ACTIVITY";
const DELETE_ACTIVITY = "DELETE_ACTIVITY";
const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
const GET_ACTIVITY = "GET_ACTIVITY";

export {
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  DELETE_ACTIVITY,
  SET_DISPLAY_NAME,
  GET_ACTIVITY
};
