const ADD_ACTIVITY = "ADD_ACTIVITY";
const EDIT_ACTIVITY = "EDIT_ACTIVITY";
const DELETE_ACTIVITY = "DELETE_ACTIVITY";
const SET_DISPLAY_NAME = "SET_DISPLAY_NAME";
const GET_ACTIVITY = "GET_ACTIVITY";
const SORT_ASC = "SORT_ASC";
const SORT_DES = "SORT_DES";
const RESET_ACTIVITY = "RESET_ACTIVITY";
export {
  ADD_ACTIVITY,
  EDIT_ACTIVITY,
  DELETE_ACTIVITY,
  SET_DISPLAY_NAME,
  GET_ACTIVITY,
  SORT_ASC,
  SORT_DES,
  RESET_ACTIVITY
};
